# Generated by Django 5.2.8 on 2025-12-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='any color', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='estore.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('other_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
                ('stock', models.IntegerField()),
                ('sold_count', models.IntegerField(default=0)),
                ('warranty_period', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='estore.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delvery_state', models.CharField(max_length=2)),
                ('delivery_estimation', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.productconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('selected', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.productconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('CP', 'Central Province'), ('EP', 'Eastern Province'), ('NCP', 'North Central Province'), ('NP', 'Northern Province'), ('NWP', 'North Western Province'), ('SMP', 'Sabaragamuwa Province'), ('SP', ' Southern Province'), ('UP', ' Uva Province'), ('WP', 'Western Province')], default='CP', max_length=3)),
                ('district', models.CharField(choices=[('1', 'Jaffna'), ('2', 'Kilinochchi'), ('3', 'Mannar'), ('4', 'Mullaitivu'), ('5', 'Vavuniya'), ('6', 'Puttalam'), ('7', 'Kurunegala'), ('8', 'Gampaha'), ('9', 'Colombo'), ('10', 'Kalutara'), ('11', 'Trincomalee'), ('12', 'Batticaloa'), ('13', 'Ampara'), ('14', 'Badulla'), ('15', 'Monaragala'), ('16', 'Hambantota'), ('17', 'Matara'), ('18', 'Galle'), ('19', 'Anuradhapura'), ('20', 'Polonnaruwa'), ('21', 'Matale'), ('22', 'Kandy'), ('23', 'Nuwara Eliya'), ('24', 'Kegalle'), ('25', 'Ratnapura')], default='1', max_length=2)),
                ('city', models.CharField(max_length=255)),
                ('street_line_01', models.CharField(max_length=255)),
                ('street_line_02', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
